sonar.projectKey=garrido-mosqueira_hexagonal-architecture
sonar.organization=garrido-mosqueira
sonar.host.url=https://sonarcloud.io

# Define the source directories for the project
sonar.sources=task-domain/src/main/java,task-application/src/main/java,task-persistence/src/main/java,task-api/src/main/java,virtual-threads-tasks/src/main/java

# Define the test directories for the project
sonar.tests=task-api/src/test/java

# Tell Sonar to look for Jacoco coverage reports in ALL target directories
sonar.coverage.jacoco.xmlReportPaths=**/target/site/jacoco/jacoco.xml
sonar.java.binaries=**/target/classes
