sonar.projectKey=garrido-mosqueira_hexagonal-architecture
sonar.organization=garrido-mosqueira
sonar.host.url=https://sonarcloud.io

# Only define the modules that have code we want to analyze
sonar.modules=task-domain,task-application,task-persistence,task-api,virtual-threads-tasks

# For each module, define where its sources and compiled classes live
task-domain.sonar.sources=src/main/java
task-domain.sonar.java.binaries=target/classes

task-application.sonar.sources=src/main/java
task-application.sonar.java.binaries=target/classes

task-persistence.sonar.sources=src/main/java
task-persistence.sonar.java.binaries=target/classes

task-api.sonar.sources=src/main/java
task-api.sonar.tests=src/test/java
task-api.sonar.java.binaries=target/classes

virtual-threads-tasks.sonar.sources=src/main/java
virtual-threads-tasks.sonar.java.binaries=target/classes

# Point to the single aggregated jacoco report created by task-api
sonar.coverage.jacoco.xmlReportPaths=task-api/target/site/jacoco-aggregate/jacoco.xml
